### PR TITLE
Added some functions to set id, name and value attributes to a input element

### PR DESCRIPTION
**Pull request by hallelujahdrive**
Added some functions because we may need to set the id, name or value attributes to a input element when building the form.
In addition, [FormField.setFor](https://package.elm-lang.org/packages/aforemny/material-components-web-elm/latest/Material-FormField#setFor) didn't work as expected, so I Fixed Checkbox and Radio Button demo pages by adding id to input elements.

### CODE REVIEW

**Comment by aforemny** [comment]
HI @hallelujahdrive, thank you for this PR. Unfortunately, the need for these changes are not perfectly clear to me. Maybe you could elaborate?

As far as I can tell you have identified the following issues. Let me phrase my questions below:

**We may need to set an id attribute to some component's native control (input) element**
What are the specific use-cases for this? I am aware of only two use-cases where being able to set the id attribute on a text field's input element could be advantageous:

- Text field focus: We cannot focus a text field by means of `Browser.Dom.focus`.
- FormField.setFor: I think this does not work as you have expected, because there is no way to set the corresponding id attribute on the control's input element.

I am however not convinced if exposing the ability to set an id attribute is the best solution for either of those problems, as I think there are other solutions that should be considered as well.

**We may need to set an name attribute to some component's native control (input) element**
What are your specific use-cases for this? I know that in HTML-only forms it is necessary for radio elements to have a name attribute, so that you can leverage the default browser functionality of radio groups.

I have personally not yet needed that with forms written in Elm, since the logic and also the communication with a back end server are usually handled within Elm, and are Model-driven rather than "form state-driven".

I am very curious about use-cases that you have in mind!

**We may need to set an value attribute to some component's native control (input) element**
Here my reasoning is the same with the name attribute. I am not aware of any use-cases.

**`FormField.setFor` is not working as expected**
How did you expect `FormField.setFor` to work? :-)

Thank you for your reply!

**Comment by hallelujahdrive** [comment]
@aforemny Thank you for your reply!
Below I will answer your questions.
>**We may need to set an id attribute to some component's native control (input) element**
> What are the specific use-cases for this? 

First, let me explain the problem I faced.
I coded a login form page that I expect to be redirected to another page with status code 302 on login success/failure, but it didn't work. The cause is that the event was processed by Html.Events.onSubmit and the body of the response could only be retrieved as a string or json. I didn't know how to render that body as a page.

The problem is solved by not using Html.Events.onSubmit, but since the name attribute cannot be set to some component's native control has, it is not possible to assemble the necessary request's body. (What I really needed for the TextField was the name attribute, not the id. I have added TextField/TextArea.setId to make it have the same function as the other input components, but may not be needed.)

If you know the URL to redirect to, all you have to do is call Browser.Navigation.load when you receive the response to solve this problem.
However, if you don't know the URL (e.g. including query parameters), you'll need to do something like this:
```
@import Browser.Navigation as Nav
@import Html exposing (Error)


type Msg = Login (Result Error String)


{- Call this function from the onSubmit/onClick event -}
login : Html.Body -> Cmd Msg
login body=
  Http.post
    { url = "https;//example.com/login"
    , body = body
    , expect = myExpectString Login
    }


{- Get the URL to redirect from a response header -}
myExpectString : (Result Error String -> Msg) -> Http.Expect Msg
myExpectString toMsg =
  Http.expectStringResponse toMsg <|
    \response ->
      case response of
        Http.BadUrl_ url ->
          Err (Http.BadUrl url)

        Http.Timeout_ ->
          Err Http.Timeout

        Http.NetworkError_ ->
          Err Http.NetworkError

        Http.BadStatus_ metadata body ->
          Err (Http.BadStatus metadata.statusCode)

        Http.GoodStatus_ metadata body ->
            Ok metadata.url


update : Msg -> Model -> (Model, Cmd Msg)
update msg model =
  case msg of
    Login res ->
      case res of
        Ok url -> (model, Nav.load url)
        Err _ -> (model, Cmd.none)
```

The code shown above has redundant error handling. In the first place, calling Browser.Navigation.load obviously gets the exact same response again, so it is wasteful communication.
This code may be necessary for Model-driven communication like elm, but it is not necessary if you can set the name attribute on the input element, e.g. using Html.input directly. (Of course, even if you change the server side program so that only the URL is returned.)

The same is true for the value attribute.
For example, if you use some Material.Radio in a form that causes a redirect, you will need to set the value attribute to assemble the request's body.

>How did you expect FormField.setFor to work? :-)

I understand the for attribute allows the label to have the same click event as the input element associated with the id. But, as you say, it doesn't work because I can't set the id on the native control.
Some components already have setOnChange, so if FormField.setFor works correctly, the demo page code should not need to handle the click event of label.

Sure, adding setId functions might have been the shallow idea, but if you don't have any way to set an id on a native input element, FormField.setFor should be omitted at all, I think. Because the existence of setFor function misleads someone that label can be associated with native control.

Thank you for reading my clunky English and I would like you to consider a little more about the addition of functions.

**Comment by hallelujahdrive** [comment]
I'm sorry!
I found that I accidentally overwrote the entire Radio.elm file, so I fixed it.

**Comment by aforemny** [comment]
Hi @hallelujahdrive, sorry for the late reply! So If I am understanding it correctly, your issue is foremost that you have to interface with a "traditional" HTML form. (Let's please ignore here the issue that you have identified with Form Field, and let's move that discussion over to #64.)

I don't think that this is a super common use case for Elm applications so that I am a bit wary to use it to justify addition of API functions.

As a work-around I would like to know if the following approach works: since `Material.TextField`s seem to be ignored by the form because you cannot give them a `name` attribute, I added for each `Material.TextField` a `Html.input` with a `name` attribute and `type="hidden"` that I whose `value` attribute I keep in sync with the `Materia.TextField` ones.

The following Ellie tries to illustrate that: https://ellie-app.com/9hhsNM8KRdMa1

I am suspecting that you could do the same "trick" for checkboxes and radio groups as well, just using a `Html.input` with the correct `name` and `value` attributes.

I realize that this is far from ideal, but maybe it works for you in the mean-time until we have more input on how common the use-case of traditional forms actually is.

Please let me know whether this is working for you!

**Comment by hallelujahdrive** [comment]
Thank you for your reply while you are busy.
I tried your suggested approach and it worked.

I don't know any other use case, so I understand what you are wary of.
However, keep in mind that this problem is specific to this wrapper library (no tricks required for either Elm or material-components-web).

For now, using the hidden input for the moment solved the problem I encountered.

Thank you for moving the discussion into the issue regarding the Form Field. I hope you find a good solution.

**Pull request closed without merging**
